List navigationData = [
  {'icon': 'analyse.png', 'title': 'Analyse', 'count': '458862'},
  {'icon': 'user.png', 'title': 'User', 'count': '458862'},
  {'icon': 'store.png', 'title': 'Store', 'count': '458862'},
  {'icon': 'vip.png', 'title': 'Vip', 'count': '458862'},
  {'icon': 'gift.png', 'title': 'Gift', 'count': '458862'},
  {'icon': 'reward.png', 'title': 'Reward', 'count': '458862'},
  {'icon': 'guardian.png', 'title': 'Guardian', 'count': '458862'},
  {'icon': 'ban.png', 'title': 'Ban', 'count': '458862'},
  {'icon': 'level.png', 'title': 'Level', 'count': '458862'},
  {'icon': 'media.png', 'title': 'Media', 'count': '458862'},
  {'icon': 'report.png', 'title': 'Report', 'count': '458862'},
  {'icon': 'agency.png', 'title': 'Agency', 'count': '458862'},
  {'icon': 'admin.png', 'title': 'Admin', 'count': '458862'},
  {'icon': 'sub_admin.png', 'title': 'Sub Admin', 'count': '458862'},
  {'icon': 'recharge.png', 'title': 'Recharge', 'count': '458862'},
  {'icon': 'pk.png', 'title': 'Pk', 'count': '458862'},
  {'icon': 'banner.png', 'title': 'Banner', 'count': '458862'},
  {'icon': 'verification.png', 'title': 'Verification', 'count': '458862'},
  {'icon': 'salary.png', 'title': 'Salary', 'count': '458862'},
  {'icon': 'sticker.png', 'title': 'Sticker', 'count': '458862'},
  {'icon': 'setting.png', 'title': 'Settings', 'count': '458862'},
  {'icon': 'payment.png', 'title': 'Payment', 'count': '458862'},
  {'icon': 'signout.png', 'title': 'Sign Out', 'count': '458862'},
  {'icon': 'ads.png', 'title': 'Ads', 'count': '458862'},
];
